from .shaping import ShapeNode, Hierarchy

class BoxBaseMeta(type):
    def __truediv__(self, rhs) -> ShapeNode: ...
    def __rtruediv__(self, lhs) -> ShapeNode: ...
    def __sub__(self, rhs) -> Hierarchy: ...
    def __rsub__(self, lhs) -> Hierarchy: ...
    def __getitem__(self, arg) -> ShapeNode: ...
